import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';

const projects = [
  {
    title: 'A Online Pandit Booking Web App',
    description: 'A full-featured Pandit Book  platform for any Pooja and Ceremony Booking with user authentication, payment processing, and user , Pandit dashboard.',
    technologies: ['React', 'Express.js', 'MongoDb', 'Razorpay', 'Nodemailer', 'JWT'],
    liveLink: 'https://book-pandit.vercel.app/',
    githubLink: 'https://github.com/Its-bhanu/bookPandit',
    image: 'https://devdarshanindia.com/web/img/core-img/online-pandit-04.jpg',
    featured: true
  },
  {
    title: 'AI Interview Mocker',
    description: 'The AI Interview Mocker is a web-based platform that simulates real interview scenarios using AI. It allows users to practice answering questions generated by Googles Gemini AI, and receive intelligent feedback on their responses..',
    technologies: ['Next.Js', 'Gemini Api', 'Drizzle Orm', 'PostgreSql','Clerk'],
    liveLink: 'https://example.com',
    githubLink: 'https://github.com/Its-bhanu/Ai-Interview-mocker',
    image: 'https://miro.medium.com/v2/resize:fit:650/1*1sIfrB5FpxSuh9q8gs87SQ.jpeg',
    featured: true
  },
  {
    title: 'ChatMe A Real Time Chat App',
    description: 'A real-time chat application that allows users to communicate instantly. Includes features like user authentication, private messaging, and group chats.',
    technologies: ['React', 'Socket.io', 'Express.JS', 'Tailwind CSS','MongoDb'],
    liveLink: 'chat-me-rosy-eta.vercel.app/login',
    githubLink: 'https://github.com/Its-bhanu/ChatApp',
    image: 'https://i.ytimg.com/vi/2I3aYt8gFdY/hqdefault.jpg',
    featured: false
  },
  {
    title: 'Portfolio Website',
    description: 'Responsive portfolio website with dark/light mode and smooth animations.',
    technologies: ['React', 'Tailwind CSS', 'Framer Motion', 'Vercel'],
    liveLink: 'https://example.com',
    githubLink: 'https://github.com/example',
    image: 'https://wiztoonz.com/wp-content/uploads/2022/04/Blog-Post-Portfolio-1170x658.jpg',
    featured: false
  },
  {
    title: 'A Small Blog Website',
    description: 'A Small Blog website where user easily post their post and shared for all visiters',
    technologies: ['React.js', 'Express.js', 'MongoDb', 'Cloudinary'],
    liveLink: 'https://mittalassign1.vercel.app/',
    githubLink: 'https://github.com/Its-bhanu/mittalassign1',
    image: 'https://www.hexaphortechnologies.co.in/service_img/1687797021.png',
    featured: false
  },
  {
    title: 'Age Calculator',
    description: 'A simple age calculator that helps users determine their age based on date of birth.',
    technologies: ['HTML', 'Css', 'Js'],
    liveLink: 'https://its-bhanu.github.io/agecalculate/',
    githubLink: 'https://github.com/Its-bhanu/agecalculate',
    image: 'https://m.media-amazon.com/images/I/41sIvI+zElL.png',
    featured: false
  },
   {
    title: 'Todo App',
    description: 'A Simple Todo app where we can add ,Edit and delete any tasks',
    technologies: ['React JS', 'Js','tailwindCss'],
    liveLink: 'https://todo-app-xi-pied.vercel.app/',
    githubLink: 'https://github.com/Its-bhanu/TodoApp',
    image: 'https://cdn.cosmicjs.com/3414b630-2fb8-11e7-8a4c-11dbea3cc073-todo-app.jpg',
    featured: false
  }
];

export function ProjectsSection() {
  return (
    <section id="projects" className="py-20 px-8">
      <div className="max-w-6xl mx-auto">
        <div className="text-center mb-16">
          <h2 className="text-4xl font-bold mb-4 bg-gradient-to-r from-purple-600 to-pink-600 bg-clip-text text-transparent">
            Projects
          </h2>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
            A collection of projects that showcase my skills and passion for development
          </p>
        </div>

        {/* Featured Projects */}
        <div className="mb-16" id='projects'>
          <h3 className="text-2xl font-bold mb-8 text-center">Featured Projects</h3>
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
            {projects.filter(project => project.featured).map((project, index) => (
              <Card 
                key={project.title} 
                className="overflow-hidden hover:shadow-xl transition-all duration-300 hover:-translate-y-2 border border-border/50"
                style={{ animationDelay: `${index * 0.1}s` }}
              >
                <div className="aspect-video overflow-hidden">
                  <img 
                    src={project.image} 
                    alt={project.title}
                    className="w-full h-full object-cover hover:scale-110 transition-transform duration-300"
                  />
                </div>
                <CardHeader>
                  <CardTitle className="flex items-center justify-between">
                    {project.title}
                    <Badge variant="secondary" className="bg-gradient-to-r from-purple-500 to-pink-500 text-white">
                      Featured
                    </Badge>
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-muted-foreground mb-4 leading-relaxed">
                    {project.description}
                  </p>
                  <div className="flex flex-wrap gap-2 mb-4">
                    {project.technologies.map((tech) => (
                      <Badge key={tech} variant="outline" className="text-xs">
                        {tech}
                      </Badge>
                    ))}
                  </div>
                  <div className="flex gap-2">
                    <Button size="sm" asChild>
                      <a href={project.liveLink} target="_blank" rel="noopener noreferrer">
                        Live Demo
                      </a>
                    </Button>
                    <Button size="sm" variant="outline" asChild>
                      <a href={project.githubLink} target="_blank" rel="noopener noreferrer">
                        GitHub
                      </a>
                    </Button>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>

        {/* Other Projects */}
        <div>
          <h3 className="text-2xl font-bold mb-8 text-center">Other Projects</h3>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {projects.filter(project => !project.featured).map((project, index) => (
              <Card 
                key={project.title} 
                className="overflow-hidden hover:shadow-lg transition-all duration-300 hover:-translate-y-1 border border-border/50"
                style={{ animationDelay: `${index * 0.1}s` }}
              >
                <div className="aspect-video overflow-hidden">
                  <img 
                    src={project.image} 
                    alt={project.title}
                    className="w-full h-full object-cover hover:scale-105 transition-transform duration-300"
                  />
                </div>
                <CardHeader className="pb-2">
                  <CardTitle className="text-lg">{project.title}</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-muted-foreground text-sm mb-3 leading-relaxed">
                    {project.description}
                  </p>
                  <div className="flex flex-wrap gap-1 mb-3">
                    {project.technologies.slice(0, 3).map((tech) => (
                      <Badge key={tech} variant="outline" className="text-xs">
                        {tech}
                      </Badge>
                    ))}
                    {project.technologies.length > 3 && (
                      <Badge variant="secondary" className="text-xs">
                        +{project.technologies.length - 3}
                      </Badge>
                    )}
                  </div>
                  <div className="flex gap-2">
                    <Button size="sm" className="flex-1" asChild>
                      <a href={project.liveLink} target="_blank" rel="noopener noreferrer">
                        Demo
                      </a>
                    </Button>
                    <Button size="sm" variant="outline" className="flex-1" asChild>
                      <a href={project.githubLink} target="_blank" rel="noopener noreferrer">
                        Code
                      </a>
                    </Button>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
}
